language: node_js

node_js:
  - "11.3.0"

branches:
  only:
    - dev

install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn

script:
  # - yarn testCoverage
  - codecov
  - yarn build

after_success:
  - cd ./dist
  - git init
  - git config --global user.name "${GIT_NAME}"
  - git config --global user.email "${GIT_EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://$GITHUB_TOKEN@$GH_REF" master:master

env:
 global:
   - GH_REF: github.com/guzhongren/gcharts.github.io.git

# deploy:
#   provider: pages # deploy to GitHub Pages
#   skip_cleanup: true # don't clean generated site
#   github_token: $GITHUB_TOKEN # provide the encrypted token
#   keep-history: true
#   on:
#     branch: dev
#   target_branch: master # optional, defaults to "gh-pages"
